### ISSUE TITLE
Problem with <reference> to remote URL

### ISSUE THREAD

**Issue by tomschr** [openSUSE/rstxml2docbook#57]
Reported by @dmpop via IRC and pastebin.

## Problem description

Seem, a reference to a remote resource in the TOC is not correctly processed:

```xml
<list_item classes="toctree-l1">
  <compact_paragraph classes="toctree-l1">
    <reference anchorname="" internal="False"
            refuri="https://developer.openstack.org/api-ref/baremetal/"
            >API Reference (latest)</reference>
  </compact_paragraph>
</list_item>
```

## Actual behaviour

```
(.env)  dpopov@e219  ~/Git/openstack-docs/ironic  rstxml2db index.xml
Traceback (most recent call last):
  File "/run/media/dpopov/DATAPART1/Git/rstxml2docbook/.env/bin/rstxml2db", line 11, in <module>
    load_entry_point('rstxml2docbook', 'console_scripts', 'rstxml2db')()
  File "/run/media/dpopov/DATAPART1/Git/rstxml2docbook/src/rstxml2db/cli.py", line 235, in main
    return process(args)
  File "/run/media/dpopov/DATAPART1/Git/rstxml2docbook/src/rstxml2db/xml/process.py", line 137, in process
    xml = transform(doc, args)
  File "/run/media/dpopov/DATAPART1/Git/rstxml2docbook/src/rstxml2db/xml/process.py", line 68, in transform
    rst = resolve_trans(doc)
  File "src/lxml/xslt.pxi", line 580, in lxml.etree.XSLT.__call__
  File "src/lxml/etree.pyx", line 314, in lxml.etree._ExceptionContext._raise_if_stored
lxml.etree.XSLTApplyError: Cannot resolve URI https://developer.openstack.org/api-ref/baremetal/.xml
```

## Steps to reproduce the behaviour

See openstack/ironic

**Comment by tomschr** [comment]
@dmpop 
Just for the record. I've found out that the file `ironic/admin/gmr.xml` contains an invalid XML character (U+001B). It's the very long list in the `Sample GMR Report` example (XPath: `/document/section[1]/section[3]/literal_block[1]`).

The character U+001B (ESCAPE) needs to be replaced by `\e`. This solves the above issue.
